version: '3.8'

services:
  client:
    image: lacrimochat_fe:latest
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "5001:3000"
    depends_on:
      - server

  server:
    image: lacrimochat_be:latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    command: >
      sh -c "
      sleep 2 &&
      bun drizzle-kit push &&
      bun dev"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "6969:5432"

volumes:
  db:
