version: '3.8'

services:
  app:
    image: lacrimochat_be:latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    command: >
      sh -c "
      bun migrate &&
      bun run dev"
    depends_on:
      db:
        condition: service_started

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"  # Expose port 80 to the host
  #   depends_on:
  #     - app

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5440:5432"

volumes:
  db:
